GEMINI_API_KEY = "AIzaSyAM2-1fuVnjp3SfqOB2PlQAK2izlCtSz6E"
EARTH911_API_KEY = "f0f0a70ae09c0123"
SUPABASE_URL = "https://pruiuekoxtmglrireyol.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBydWl1ZWtveHRtZ2xyaXJleW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODcwNDEsImV4cCI6MjA2NjI2MzA0MX0.M720_6mIfXzCBwz2Oqm7qttBgdfB0t_GEhEsRGGM2I0"
WEBHOOK_URL = "https://hook.us2.make.com/9gp62qdde6hz6rpto1whape78mu3vqu3"
NEWS_API_KEY = "c09e320ec89c9a15753ca37616717c2b"